'use client';

import React, { useEffect, useState } from "react";
import { BookCheck, CircleX, Loader } from "lucide-react";
import FormInput from "../admin/common/FormInput";
import FormTextarea from "../admin/common/FormTextarea";
import FormSelect from "../admin/common/FormSelect";
import { getCategories } from "@/api/quiz";
import TagInput from "../admin/common/TagInput";
import { Category } from "@/types/public/category";

export interface UserQuizFormData {
  title: string;
  description: string;
  category: Category;
  difficulty: "Beginner" | "Intermediate" | "Advanced" | "";
  duration: number;
  passingScore: number;
  maxAttempts: number;
  color: string;
  price_token: number;
  // Optional fields that can be auto-generated by AI
  learning_objectives?: string[];
  prerequisites?: string[];
  tags?: string[];
}

interface UserQuizFormProps {
  onSubmit: (data: UserQuizFormData) => void;
  isLoading?: boolean;
  initialData?: Partial<UserQuizFormData>;
}

export default function UserQuizForm({
  onSubmit,
  isLoading = false,
  initialData,
}: UserQuizFormProps) {
  const [formData, setFormData] = useState<UserQuizFormData>({
    title: initialData?.title || "",
    description: initialData?.description || "",
    category: initialData?.category || { id: 0, name: "" },
    difficulty: initialData?.difficulty || "",
    duration: initialData?.duration || 30,
    passingScore: initialData?.passingScore || 70,
    maxAttempts: initialData?.maxAttempts || 3,
    color: initialData?.color || "#3B82F6",
    price_token: initialData?.price_token || 0,
    // Optional AI-generated fields
    learning_objectives: initialData?.learning_objectives || [],
    prerequisites: initialData?.prerequisites || [],
    tags: initialData?.tags || [],
  });

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [categories, setCategories] = useState<{ id: string; name: string }[]>([]);

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const data = await getCategories();
        setCategories(data);
      } catch (error) {
        console.error("Failed to fetch categories:", error);
      }
    };

    fetchCategories();
  }, []);

  const handleInputChange = (field: keyof UserQuizFormData, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error when user starts typing
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: "" }));
    }
  };

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.title.trim()) {
      newErrors.title = "Tiêu đề quiz là bắt buộc";
    }

    if (!formData.description.trim()) {
      newErrors.description = "Mô tả quiz là bắt buộc";
    }

    if (!formData.category.id) {
      newErrors.category = "Vui lòng chọn danh mục";
    }

    if (!formData.difficulty) {
      newErrors.difficulty = "Vui lòng chọn độ khó";
    }

    if (formData.duration < 5) {
      newErrors.duration = "Thời gian tối thiểu là 5 phút";
    }

    if (formData.passingScore < 0 || formData.passingScore > 100) {
      newErrors.passingScore = "Điểm đạt phải từ 0-100%";
    }

    if (formData.maxAttempts < 1) {
      newErrors.maxAttempts = "Số lần thử tối thiểu là 1";
    }

    if (formData.price_token < 0) {
      newErrors.price_token = "Giá token không được âm";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (validateForm()) {
      onSubmit(formData);
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200">
      <div className="p-8">
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">
            Thông tin Quiz cơ bản
          </h2>
          <p className="text-gray-600">
            Điền thông tin cơ bản của quiz. AI sẽ tự động tạo mục tiêu học tập, kiến thức cần có và thẻ tag từ nội dung file của bạn.
          </p>
        </div>

        {Object.keys(errors).length > 0 && (
          <div className="mb-6 p-4 bg-red-50 border-l-4 border-red-500 rounded-md">
            <div className="flex items-start">
              <CircleX className="h-5 w-5 text-red-500 mr-2 mt-0.5" />
              <div>
                <p className="text-red-800 font-medium">Vui lòng kiểm tra lại thông tin</p>
                <ul className="text-red-600 text-sm mt-1">
                  {Object.values(errors).map((error, index) => (
                    <li key={index}>• {error}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit}>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Left Column */}
            <div className="space-y-6">
              {/* Title */}
              <FormInput
                label="Tiêu đề Quiz"
                name="title"
                type="text"
                value={formData.title}
                onChange={(e) => handleInputChange("title", e.target.value)}
                required
                placeholder="Nhập tiêu đề quiz"
                error={errors.title}
                icon={<BookCheck className="h-5 w-5" />}
              />

              {/* Description */}
              <FormTextarea
                label="Mô tả"
                name="description"
                value={formData.description}
                onChange={(e) => handleInputChange("description", e.target.value)}
                placeholder="Nhập mô tả chi tiết về quiz"
                error={errors.description}
                required
              />

              {/* Category & Difficulty */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <FormSelect
                  label="Danh mục"
                  name="category"
                  value={formData.category?.id?.toString() || ""}
                  onChange={(e) => {
                    const selectedId = Number(e.target.value);
                    const selectedCategory = categories.find(
                      (cat) => Number(cat.id) === selectedId
                    );
                    handleInputChange("category", selectedCategory || { id: 0, name: "" });
                  }}
                  error={errors.category}
                  required
                  options={categories.map((cat) => ({
                    label: cat.name,
                    value: cat.id,
                  }))}
                />
                <FormSelect
                  label="Độ khó"
                  name="difficulty"
                  value={formData.difficulty}
                  onChange={(e) => handleInputChange("difficulty", e.target.value)}
                  error={errors.difficulty}
                  required
                  options={[
                    { label: "Cơ bản", value: "Beginner" },
                    { label: "Trung bình", value: "Intermediate" },
                    { label: "Nâng cao", value: "Advanced" },
                  ]}
                />
              </div>

              {/* Duration & Passing Score */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <FormInput
                  label="Thời gian (phút)"
                  name="duration"
                  type="number"
                  value={formData.duration.toString()}
                  onChange={(e) =>
                    handleInputChange("duration", parseInt(e.target.value) || 30)
                  }
                  error={errors.duration}
                  required
                  placeholder="30"
                />
                <FormInput
                  label="Điểm đạt (%)"
                  name="passingScore"
                  type="number"
                  value={formData.passingScore.toString()}
                  onChange={(e) =>
                    handleInputChange("passingScore", parseInt(e.target.value) || 70)
                  }
                  error={errors.passingScore}
                  required
                  placeholder="70"
                />
              </div>

              {/* Max Attempts & Price */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <FormInput
                  label="Số lần thử tối đa"
                  name="maxAttempts"
                  type="number"
                  value={formData.maxAttempts.toString()}
                  onChange={(e) =>
                    handleInputChange("maxAttempts", parseInt(e.target.value) || 3)
                  }
                  error={errors.maxAttempts}
                  required
                  placeholder="3"
                />
                <FormInput
                  label="Giá (Tokens)"
                  name="price_token"
                  type="number"
                  value={formData.price_token?.toString() ?? ""}
                  onChange={(e) =>
                    handleInputChange(
                      "price_token",
                      e.target.value === "" ? 0 : Number(e.target.value)
                    )
                  }
                  error={errors.price_token}
                  placeholder="0"
                />
              </div>

              {/* Color */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Màu chủ đề (Tùy chọn)
                </label>
                <div className="flex items-center gap-3">
                  <input
                    type="color"
                    value={formData.color}
                    onChange={(e) => handleInputChange("color", e.target.value)}
                    className="w-10 h-10 border shadow-md border-gray-300 rounded-lg cursor-pointer"
                  />
                  <input
                    type="text"
                    value={formData.color}
                    onChange={(e) => handleInputChange("color", e.target.value)}
                    className="flex-1 px-4 py-2 shadow-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    placeholder="#3B82F6"
                  />
                </div>
              </div>
            </div>

            {/* Right Column */}
            <div className="space-y-6">
              {/* AI Generation Info */}
              <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-xl p-6">
                <div className="flex items-start space-x-4">
                  <div className="flex-shrink-0">
                    <div className="w-10 h-10 bg-purple-100 rounded-full flex items-center justify-center">
                      <svg className="w-5 h-5 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                      </svg>
                    </div>
                  </div>
                  <div className="text-left">
                    <h3 className="font-semibold text-purple-900 mb-2">🤖 AI sẽ tự động tạo</h3>
                    <ul className="text-purple-800 text-sm space-y-1">
                      <li>• <strong>Mục tiêu học tập</strong> (3-5 mục)</li>
                      <li>• <strong>Kiến thức cần có</strong> (2-4 mục)</li>
                      <li>• <strong>Thẻ tag</strong> (3-6 từ khóa)</li>
                      <li>• <strong>Câu hỏi quiz</strong> chất lượng cao</li>
                    </ul>
                    <p className="text-purple-700 text-xs mt-2 italic">
                      Dựa trên nội dung file bạn upload
                    </p>
                  </div>
                </div>
              </div>

              {/* Optional: Manual Override */}
              <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-gray-900">
                    Tùy chỉnh thêm (Tùy chọn)
                  </h3>
                  <span className="text-xs bg-gray-200 text-gray-600 px-2 py-1 rounded-full">
                    Không bắt buộc
                  </span>
                </div>
                
                <div className="space-y-4">
                  {/* Learning Objectives */}
                  <div>
                    <TagInput
                      label="Mục tiêu học tập"
                      items={formData.learning_objectives || []}
                      onItemsChange={(items) =>
                        handleInputChange("learning_objectives", items)
                      }
                      placeholder="AI sẽ tự tạo, hoặc bạn có thể thêm thủ công"
                      maxItems={10}
                      required={false}
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Để trống để AI tự động tạo từ nội dung file
                    </p>
                  </div>

                  {/* Prerequisites */}
                  <div>
                    <TagInput
                      label="Kiến thức cần có"
                      items={formData.prerequisites || []}
                      onItemsChange={(items) =>
                        handleInputChange("prerequisites", items)
                      }
                      placeholder="AI sẽ tự tạo, hoặc bạn có thể thêm thủ công"
                      maxItems={10}
                      required={false}
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Để trống để AI tự động tạo từ nội dung file
                    </p>
                  </div>

                  {/* Tags */}
                  <div>
                    <TagInput
                      label="Thẻ tag"
                      items={formData.tags || []}
                      onItemsChange={(items) => handleInputChange("tags", items)}
                      placeholder="AI sẽ tự tạo, hoặc bạn có thể thêm thủ công"
                      maxItems={10}
                      required={false}
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Để trống để AI tự động tạo từ nội dung file
                    </p>
                  </div>
                </div>
              </div>

              {/* Preview Card */}
              <div
                className="bg-gray-50 rounded-lg p-6 border-l-4"
                style={{ borderLeftColor: formData.color }}
              >
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  Xem trước Quiz
                </h3>
                <div className="space-y-2 text-sm text-gray-600">
                  <p>
                    <span className="font-medium">Tiêu đề:</span>{" "}
                    {formData.title || "Tiêu đề quiz"}
                  </p>
                  <p>
                    <span className="font-medium">Danh mục:</span>{" "}
                    {formData.category.name || "Chưa chọn"}
                  </p>
                  <p>
                    <span className="font-medium">Độ khó:</span>{" "}
                    {formData.difficulty === "Beginner" ? "Cơ bản" :
                     formData.difficulty === "Intermediate" ? "Trung bình" :
                     formData.difficulty === "Advanced" ? "Nâng cao" : "Chưa chọn"}
                  </p>
                  <p>
                    <span className="font-medium">Thời gian:</span>{" "}
                    {formData.duration} phút
                  </p>
                  <p>
                    <span className="font-medium">Điểm đạt:</span>{" "}
                    {formData.passingScore}%
                  </p>
                  <p>
                    <span className="font-medium">Số lần thử:</span>{" "}
                    {formData.maxAttempts} lần
                  </p>
                  <p>
                    <span className="font-medium">Giá:</span>{" "}
                    {formData.price_token} tokens
                  </p>
                  
                  {/* Show manual overrides if any */}
                  {formData.learning_objectives && formData.learning_objectives.length > 0 && (
                    <p>
                      <span className="font-medium">Mục tiêu (thủ công):</span>{" "}
                      {formData.learning_objectives.length} mục
                    </p>
                  )}
                  {formData.prerequisites && formData.prerequisites.length > 0 && (
                    <p>
                      <span className="font-medium">Kiến thức cần có (thủ công):</span>{" "}
                      {formData.prerequisites.length} mục
                    </p>
                  )}
                  {formData.tags && formData.tags.length > 0 && (
                    <p>
                      <span className="font-medium">Tags (thủ công):</span>{" "}
                      {formData.tags.length} tag
                    </p>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Action Button */}
          <div className="flex justify-end mt-8 pt-6 border-t border-gray-200">
            <button
              type="submit"
              disabled={isLoading}
              className={`px-8 py-3 bg-gradient-to-r from-blue-500 to-purple-600 text-white font-semibold rounded-xl shadow-lg hover:from-blue-600 hover:to-purple-700 focus:outline-none focus:ring-4 focus:ring-blue-300 transition-all duration-200 ${
                isLoading
                  ? "opacity-70 cursor-not-allowed"
                  : "transform hover:scale-105"
              }`}
            >
              {isLoading ? (
                <div className="flex items-center">
                  <Loader className="animate-spin mr-2 h-5 w-5" />
                  Đang xử lý...
                </div>
              ) : (
                "Tiếp tục upload file và tạo quiz bằng AI"
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}